development:
  laxino:
    auth_source:
      token: '10.10.5.46'
      type: 'Adfs'
    auth_source_detail:
      name: 'laxino_adfs'
      data:
        config_url: "https://fs.laxino.com/federationmetadata/2007-06/federationmetadata.xml"
        comparison: "minimum"
        private_key: "-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDX7h4hXJSMey7R
6x6VzW0rw7fgIEjy4U3hH5CAYwDdotqACDQ9pbUPMkcoLa0xk/fvdyr/VBjNXBCI
/5F9ouwA6anDa0/D6bzD23rVg4lB98CpahaaYlkd35CpJDQgGRpKo3kyFw7cv+TH
Kmf+oAMj+4W20K6JrkiBHKZ8GTWKPZeiM7G9xxDVxWKzn2dMnX41f4s3jGSSLlLL
WSJiPuqZIieVGzVv6wQ6BYFQJUD97OJbU1oEYCK2442J3wrgDRbV0jizcS0/kxrL
I+WVG/AD2bVasS+sJO1bm1qmWFoiKb5R1/1by9hky7AXzilBvEyuUKJlV5DDd53e
/CEKlpFRAgMBAAECggEBALfZTl4pbXGPEHY7MndpySISKmTyGCp0GtMrBOXLZdlP
56pLUe+LP3YI4P0cpvInglqppDpxaAyx7oI217GZHkhIqvpwTCIKyWYZYaSZsiww
viGA6m3YfvgoegsJgDg0J2aVeYNkjor199x8Br+Njh788QSO+YzQj3se4cGX1TY1
WcwxMRmWcp36P4mCOxNbjjPdzs/i0jpgczRp8Gg8mcPMRz6GsrPKT0cA8s+KQokj
T57Pbyo64KWnIKFkSNuR19nqpKpxXojV0gkSfYJ8aAL7fn+AYURlR5J3Uvv4ChC7
ZSKwKeJJy/qSnsCsxASd6IF69HfmuMnUL+fQ4odqzOECgYEA+rOXEFXCgQW457yk
NUQj9qa7s4QV6WU5nc1Ol2VEFS6E2zyVxttqLQKJjaw5ubzMHnN27z836wDw4Rjc
m1jT7+B0bJ/vjRwimtwHEQlw58Z2yGcMuNVlmqW5Z1tutMOCSL7pYpfVBm5f7btW
mzVA6zKaDEGYxeiAkKLGbI2sP0cCgYEA3H5mB5LHP9FPnuEZMnKpTxyjdWwbC6ZI
N1/BoS7osYUDNQbeGX4EsuAOykY7YitWKfc0/VDM/6nftM6m2kKA9pqgWGc72X6N
QucgnfuaGdK2fYu+JwaTz/ow6L5wNNYYg0XVHK5dvfCOEerIf8PgJHMlSmjEn/v5
d1LjaEFlZqcCgYAS5qlT/PM+IP1Q02MZ9Po1JVrvbNzuDMisQgdT2LmqUyiHEulD
5dT6cb+HI93yR+6nuRLVdNG1cQu4HNS9DZRk+Gouqlw4Kk/dlwsdWLXfc5IPB93o
rYYMg8QXq8gL7tWKwIH+Ae54nqey17Xu27P6R4VfuS5YdXAD95G4K3I6DwKBgExF
dOm9viq3LsGYv+yReTuifnCJ2rkm5egxuXsWDOwLRNa872sGCn4Nv0/9B2Gn+ABA
QRY3MxJlIrsamOD7DD1Bs6Gg5DUR769q3/+GHwI7v2CiTD6Xqd3Rf8WiypGcVZJj
P5rSPh8L7TkJbB22FfzFz+pzX0CwGtVJ2NwhcwAVAoGBAL69IKUGj2ouIZhrk80x
Xz/6UJBMPmM0o72iJAjTmqZHppQZGPMeQ3LuAuzwkXb1UE6bFDx9ZLDUsom8+GKH
EglSFLjWAya+/Yu67nlSM5iJT2jTjKS2ewqnY2ASR8gsuWVFEhzerFb+hBoR8Ji1
9AAfAgR9Co1Vp/jsEidZ8umP
-----END PRIVATE KEY-----"
        certificate: "-----BEGIN CERTIFICATE-----
MIIDvTCCAqWgAwIBAgIJALwJNIgx3iQ4MA0GCSqGSIb3DQEBCwUAMHUxCzAJBgNV
BAYTAk1PMQswCQYDVQQIDAJNTzELMAkGA1UEBwwCTU8xEzARBgNVBAoMCmdhbWVz
b3VyY2UxEzARBgNVBAsMCmdhbWVzb3VyY2UxIjAgBgkqhkiG9w0BCQEWE2luZm9A
Z2FtZXNvdXJjZS5jb20wHhcNMjEwNzA4MTAyMTUwWhcNMzEwNzA2MTAyMTUwWjB1
MQswCQYDVQQGEwJNTzELMAkGA1UECAwCTU8xCzAJBgNVBAcMAk1PMRMwEQYDVQQK
DApnYW1lc291cmNlMRMwEQYDVQQLDApnYW1lc291cmNlMSIwIAYJKoZIhvcNAQkB
FhNpbmZvQGdhbWVzb3VyY2UuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEA1+4eIVyUjHsu0eselc1tK8O34CBI8uFN4R+QgGMA3aLagAg0PaW1DzJH
KC2tMZP373cq/1QYzVwQiP+RfaLsAOmpw2tPw+m8w9t61YOJQffAqWoWmmJZHd+Q
qSQ0IBkaSqN5MhcO3L/kxypn/qADI/uFttCuia5IgRymfBk1ij2XojOxvccQ1cVi
s59nTJ1+NX+LN4xkki5Sy1kiYj7qmSInlRs1b+sEOgWBUCVA/eziW1NaBGAituON
id8K4A0W1dI4s3EtP5MayyPllRvwA9m1WrEvrCTtW5taplhaIim+Udf9W8vYZMuw
F84pQbxMrlCiZVeQw3ed3vwhCpaRUQIDAQABo1AwTjAdBgNVHQ4EFgQUeJqa4QQI
/k3ARq1aajuMHE1OEYYwHwYDVR0jBBgwFoAUeJqa4QQI/k3ARq1aajuMHE1OEYYw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAQ17T/reA+jOXDDEa7fzK
rYMQ3kl41/FNRb5LSSNnkd0re1RjEkUcdp2IDWdddxVGAWNn23DRwskE2asdmEEs
RkxpLQCLNh0BXTgUjn3OdPxKYMY+KElkPTeyRIrfVNq3XU60W4tQP3DvH/YDpGwe
1H/Zn2LSw8kwFAjzyectjXONUXqKJ7FxvIuVw8fLL/PmMZqu2mYnA7ygw0jwPkTm
Qs+pqLmGxyEcZp8qntaak9KkmFw+mQgCwz8QUofXqqXbDSBnjTf7zUzO6Rs+2E7N
YOnaQ58bvBrQgf7/sxINcGcxNpUoIaBpOAQ6pqdWuu6QV1eV49xOgavLW47s4xjF
7Q==
-----END CERTIFICATE-----"
        digest_method: "XMLSecurity::Document::SHA256"
        signature_method: "XMLSecurity::Document::RSA_SHA256"

integration0:
  laxino:
    auth_source:
      token: '127.0.0.1'
      type: 'Adfs'
    auth_source_detail:
      name: 'laxino_adfs'
      data:
        config_url: "https://fs.laxino.com/federationmetadata/2007-06/federationmetadata.xml"
        comparison: "minimum"
        private_key: "-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCeMSKCuiZddv1/
GwdlCQpUxVYbpWFXxuVpyC4AEWZMVeP46aWJUXn5WTJHq6BvQT8Y/9nTvh57Uzf1
tRbZsCpj+Kst4Hg1dSElaz3ytra+J9jz6lexxucqLKASlWSKFtlSsKcHCX73pOu2
HADcmNKRekLcWaT8yElXpVqBnhhOzanE1OQQtDwvK0+FY4Rcox8Kqcgb+O4R+qGO
lyWaG9/acLIw42xuDLK12+kzLLY0wTfeXcUPsP/zq598buGDQWbfXIrLMFwXIh9P
x5XO7nimvJPwiFyAXUS0ILVMhFeEwQXT5VgYkI4Z3WITjewUZhXVTPOx1lUmN+tW
KZpQ2OC/AgMBAAECggEAKUkJiLSsbpgvcIzNUUEawST/ZBe1YAM4vHLSDpJ78FA6
Pyw7V6s7+iedR7czF9YfcZbUcr6blfQSFr48SHQBnDW59y8uMEVxcSKb+ExXRSmB
JadzW6JdklQzMqZqpt9vuHUCIoQH7vnLyqtkTi5URkNyT6/Vr2NWQNmW1V09WtNI
/7UZxms0WyMi8AvS2iPhFR25mw0uq9CsQ0cFVeAN3IG7bnPYn8EcdhMjsYfHbYfO
qkiou1L6ALsAIofcCb2psPSKI/TFHyLIWzF4pcS+5mlc/b+c+1E1H9R7q1+iLj+9
YWXH+IwTjl2OhB1n87bkHklJv2KNfHxkv30F6OcjgQKBgQDLF26weGa8QNbx94BP
cDQZFFRGsNdTiOf+5P8Ozft+uvGyaB2PpR/fAXqjty5tgco0/aQ1+v//GkZk28nm
uIT3I1h425kta8Zj2f3kK6kAxKNFl9fsKXsF8IexL0VQIMuL+3n6iF5TcfVlT1oL
LfayJfv9eFW4lFxo1O7QiNpGCwKBgQDHZ0LbS5iIslkvDFl27gJfZEV60j5vS4mI
vWvlgwFuWH9b+tWP2+//LoTOomCTGMDyUpsZrYqbfsxuJt70TVhIuHNCqXC68aVg
9+px1Cnb0TY7UkYwtvDYu0/NwVuQKbzJGE/sy4aVQtSi8BZ7WHFtbQUqx5EuqiLa
7uIZ6sNEnQKBgQC7iDOpuEQFaUoRvJ06vT0eO2tmqzzp4e13rTToEsQ8TZuJRiKl
1bAMWG1KZ4fzjnmNXPkY72EbysNdtqZE6fW9z2GOmBhlnLNg2JZc7wPrtaeeR4wW
gmcbIPPrZN74EpBh/iCweuO+4efbWN6onBTEg9agQ1HEUxrRom2zGeuT6QKBgQCU
gCN7O65KR0BB2JmcB57+uadA0+ipbADuM9tx3oGnUwLuVjzL2Ui/qz4+wRDZG3s+
PCTEF8j9Co5mjk5GdH+GEM/N2nBY2POH5rnTseTGjuUrgpdBWky9q6nAGvr8vwiY
XqHPQLdm25GOEu07SN+YVbOea2eE8DHrCDKciIiJxQKBgQC1HFhlvAH8kvhihVj1
wGdfuFBo+AEfLl+MnnsHNx0uigMUPolddt+5CmQasttMKV+4IHSmDwlG0bMpAV9H
6+fX5TLYZgkrJaKKowQ1PUBUW1XMS6GpIlsOuzzTaxSJi00wQEDJ/rXWDx4eBj5l
RevUD6glxmm8ToJ+vkBXQiGjvQ==
-----END PRIVATE KEY-----"
        certificate: "-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIJAO81fl9gp0vPMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTcwNjEzMDQzODA5WhcNMTkwNjEzMDQzODA5WjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAnjEigromXXb9fxsHZQkKVMVWG6VhV8blacguABFmTFXj+OmliVF5+Vky
R6ugb0E/GP/Z074ee1M39bUW2bAqY/irLeB4NXUhJWs98ra2vifY8+pXscbnKiyg
EpVkihbZUrCnBwl+96TrthwA3JjSkXpC3Fmk/MhJV6VagZ4YTs2pxNTkELQ8LytP
hWOEXKMfCqnIG/juEfqhjpclmhvf2nCyMONsbgyytdvpMyy2NME33l3FD7D/86uf
fG7hg0Fm31yKyzBcFyIfT8eVzu54pryT8IhcgF1EtCC1TIRXhMEF0+VYGJCOGd1i
E43sFGYV1UzzsdZVJjfrVimaUNjgvwIDAQABo1AwTjAdBgNVHQ4EFgQUg0gu4ij9
VguxRGzihuguI2EqlUIwHwYDVR0jBBgwFoAUg0gu4ij9VguxRGzihuguI2EqlUIw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAIwsdxd1j3AzDKE4kdZhH
WS72ETLP7Wt8UIBKpSOKD+T983dAkum36svkYAB+y+UWeX4nDb/kTc+vibmn9lPm
Sq9amuy/wkKR6GVepVlIXR4KX6PDob08B/NiXMdWJMv6T/txO25tqdm5lCYjSlt+
nzeOETfak/W81RS7uzypyLbf7BLWw9JxqXilFrDLrIvWfZNb0Or9wFUYao9a2XPQ
lS7TfOaVuy26NXRJEndTEd+UAhRmXroi54B8/WO57WPES9WMp29pqEksiKaWxkh/
Synm9GOf+vrb2y4tSRmvboORYVAQaQT8FkTz39ul0cZMafkZ0wJQVuf97ISXQ9jU
Xg==
-----END CERTIFICATE-----"
        digest_method: "XMLSecurity::Document::SHA256"
        signature_method: "XMLSecurity::Document::RSA_SHA256"

staging0:
  laxino:
    auth_source:
      token: '10.10.45.250'
      type: 'Adfs'
    auth_source_detail:
      name: 'laxino_adfs'
      data:
        config_url: "https://fs.laxino.com/federationmetadata/2007-06/federationmetadata.xml"
        comparison: "minimum"
        private_key: "-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCeMSKCuiZddv1/
GwdlCQpUxVYbpWFXxuVpyC4AEWZMVeP46aWJUXn5WTJHq6BvQT8Y/9nTvh57Uzf1
tRbZsCpj+Kst4Hg1dSElaz3ytra+J9jz6lexxucqLKASlWSKFtlSsKcHCX73pOu2
HADcmNKRekLcWaT8yElXpVqBnhhOzanE1OQQtDwvK0+FY4Rcox8Kqcgb+O4R+qGO
lyWaG9/acLIw42xuDLK12+kzLLY0wTfeXcUPsP/zq598buGDQWbfXIrLMFwXIh9P
x5XO7nimvJPwiFyAXUS0ILVMhFeEwQXT5VgYkI4Z3WITjewUZhXVTPOx1lUmN+tW
KZpQ2OC/AgMBAAECggEAKUkJiLSsbpgvcIzNUUEawST/ZBe1YAM4vHLSDpJ78FA6
Pyw7V6s7+iedR7czF9YfcZbUcr6blfQSFr48SHQBnDW59y8uMEVxcSKb+ExXRSmB
JadzW6JdklQzMqZqpt9vuHUCIoQH7vnLyqtkTi5URkNyT6/Vr2NWQNmW1V09WtNI
/7UZxms0WyMi8AvS2iPhFR25mw0uq9CsQ0cFVeAN3IG7bnPYn8EcdhMjsYfHbYfO
qkiou1L6ALsAIofcCb2psPSKI/TFHyLIWzF4pcS+5mlc/b+c+1E1H9R7q1+iLj+9
YWXH+IwTjl2OhB1n87bkHklJv2KNfHxkv30F6OcjgQKBgQDLF26weGa8QNbx94BP
cDQZFFRGsNdTiOf+5P8Ozft+uvGyaB2PpR/fAXqjty5tgco0/aQ1+v//GkZk28nm
uIT3I1h425kta8Zj2f3kK6kAxKNFl9fsKXsF8IexL0VQIMuL+3n6iF5TcfVlT1oL
LfayJfv9eFW4lFxo1O7QiNpGCwKBgQDHZ0LbS5iIslkvDFl27gJfZEV60j5vS4mI
vWvlgwFuWH9b+tWP2+//LoTOomCTGMDyUpsZrYqbfsxuJt70TVhIuHNCqXC68aVg
9+px1Cnb0TY7UkYwtvDYu0/NwVuQKbzJGE/sy4aVQtSi8BZ7WHFtbQUqx5EuqiLa
7uIZ6sNEnQKBgQC7iDOpuEQFaUoRvJ06vT0eO2tmqzzp4e13rTToEsQ8TZuJRiKl
1bAMWG1KZ4fzjnmNXPkY72EbysNdtqZE6fW9z2GOmBhlnLNg2JZc7wPrtaeeR4wW
gmcbIPPrZN74EpBh/iCweuO+4efbWN6onBTEg9agQ1HEUxrRom2zGeuT6QKBgQCU
gCN7O65KR0BB2JmcB57+uadA0+ipbADuM9tx3oGnUwLuVjzL2Ui/qz4+wRDZG3s+
PCTEF8j9Co5mjk5GdH+GEM/N2nBY2POH5rnTseTGjuUrgpdBWky9q6nAGvr8vwiY
XqHPQLdm25GOEu07SN+YVbOea2eE8DHrCDKciIiJxQKBgQC1HFhlvAH8kvhihVj1
wGdfuFBo+AEfLl+MnnsHNx0uigMUPolddt+5CmQasttMKV+4IHSmDwlG0bMpAV9H
6+fX5TLYZgkrJaKKowQ1PUBUW1XMS6GpIlsOuzzTaxSJi00wQEDJ/rXWDx4eBj5l
RevUD6glxmm8ToJ+vkBXQiGjvQ==
-----END PRIVATE KEY-----"
        certificate: "-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIJAO81fl9gp0vPMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTcwNjEzMDQzODA5WhcNMTkwNjEzMDQzODA5WjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAnjEigromXXb9fxsHZQkKVMVWG6VhV8blacguABFmTFXj+OmliVF5+Vky
R6ugb0E/GP/Z074ee1M39bUW2bAqY/irLeB4NXUhJWs98ra2vifY8+pXscbnKiyg
EpVkihbZUrCnBwl+96TrthwA3JjSkXpC3Fmk/MhJV6VagZ4YTs2pxNTkELQ8LytP
hWOEXKMfCqnIG/juEfqhjpclmhvf2nCyMONsbgyytdvpMyy2NME33l3FD7D/86uf
fG7hg0Fm31yKyzBcFyIfT8eVzu54pryT8IhcgF1EtCC1TIRXhMEF0+VYGJCOGd1i
E43sFGYV1UzzsdZVJjfrVimaUNjgvwIDAQABo1AwTjAdBgNVHQ4EFgQUg0gu4ij9
VguxRGzihuguI2EqlUIwHwYDVR0jBBgwFoAUg0gu4ij9VguxRGzihuguI2EqlUIw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAIwsdxd1j3AzDKE4kdZhH
WS72ETLP7Wt8UIBKpSOKD+T983dAkum36svkYAB+y+UWeX4nDb/kTc+vibmn9lPm
Sq9amuy/wkKR6GVepVlIXR4KX6PDob08B/NiXMdWJMv6T/txO25tqdm5lCYjSlt+
nzeOETfak/W81RS7uzypyLbf7BLWw9JxqXilFrDLrIvWfZNb0Or9wFUYao9a2XPQ
lS7TfOaVuy26NXRJEndTEd+UAhRmXroi54B8/WO57WPES9WMp29pqEksiKaWxkh/
Synm9GOf+vrb2y4tSRmvboORYVAQaQT8FkTz39ul0cZMafkZ0wJQVuf97ISXQ9jU
Xg==
-----END CERTIFICATE-----"
        digest_method: "XMLSecurity::Document::SHA256"
        signature_method: "XMLSecurity::Document::RSA_SHA256"

staging1:
  laxino:
    auth_source:
      token: '10.10.5.162'
      type: 'Adfs'
    auth_source_detail:
      name: 'laxino_adfs_4'
      data:
        config_url: "https://adfs.ias.local/federationmetadata/2007-06/federationmetadata.xml"
        comparison: "minimum"
        private_key: "-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDX7h4hXJSMey7R
6x6VzW0rw7fgIEjy4U3hH5CAYwDdotqACDQ9pbUPMkcoLa0xk/fvdyr/VBjNXBCI
/5F9ouwA6anDa0/D6bzD23rVg4lB98CpahaaYlkd35CpJDQgGRpKo3kyFw7cv+TH
Kmf+oAMj+4W20K6JrkiBHKZ8GTWKPZeiM7G9xxDVxWKzn2dMnX41f4s3jGSSLlLL
WSJiPuqZIieVGzVv6wQ6BYFQJUD97OJbU1oEYCK2442J3wrgDRbV0jizcS0/kxrL
I+WVG/AD2bVasS+sJO1bm1qmWFoiKb5R1/1by9hky7AXzilBvEyuUKJlV5DDd53e
/CEKlpFRAgMBAAECggEBALfZTl4pbXGPEHY7MndpySISKmTyGCp0GtMrBOXLZdlP
56pLUe+LP3YI4P0cpvInglqppDpxaAyx7oI217GZHkhIqvpwTCIKyWYZYaSZsiww
viGA6m3YfvgoegsJgDg0J2aVeYNkjor199x8Br+Njh788QSO+YzQj3se4cGX1TY1
WcwxMRmWcp36P4mCOxNbjjPdzs/i0jpgczRp8Gg8mcPMRz6GsrPKT0cA8s+KQokj
T57Pbyo64KWnIKFkSNuR19nqpKpxXojV0gkSfYJ8aAL7fn+AYURlR5J3Uvv4ChC7
ZSKwKeJJy/qSnsCsxASd6IF69HfmuMnUL+fQ4odqzOECgYEA+rOXEFXCgQW457yk
NUQj9qa7s4QV6WU5nc1Ol2VEFS6E2zyVxttqLQKJjaw5ubzMHnN27z836wDw4Rjc
m1jT7+B0bJ/vjRwimtwHEQlw58Z2yGcMuNVlmqW5Z1tutMOCSL7pYpfVBm5f7btW
mzVA6zKaDEGYxeiAkKLGbI2sP0cCgYEA3H5mB5LHP9FPnuEZMnKpTxyjdWwbC6ZI
N1/BoS7osYUDNQbeGX4EsuAOykY7YitWKfc0/VDM/6nftM6m2kKA9pqgWGc72X6N
QucgnfuaGdK2fYu+JwaTz/ow6L5wNNYYg0XVHK5dvfCOEerIf8PgJHMlSmjEn/v5
d1LjaEFlZqcCgYAS5qlT/PM+IP1Q02MZ9Po1JVrvbNzuDMisQgdT2LmqUyiHEulD
5dT6cb+HI93yR+6nuRLVdNG1cQu4HNS9DZRk+Gouqlw4Kk/dlwsdWLXfc5IPB93o
rYYMg8QXq8gL7tWKwIH+Ae54nqey17Xu27P6R4VfuS5YdXAD95G4K3I6DwKBgExF
dOm9viq3LsGYv+yReTuifnCJ2rkm5egxuXsWDOwLRNa872sGCn4Nv0/9B2Gn+ABA
QRY3MxJlIrsamOD7DD1Bs6Gg5DUR769q3/+GHwI7v2CiTD6Xqd3Rf8WiypGcVZJj
P5rSPh8L7TkJbB22FfzFz+pzX0CwGtVJ2NwhcwAVAoGBAL69IKUGj2ouIZhrk80x
Xz/6UJBMPmM0o72iJAjTmqZHppQZGPMeQ3LuAuzwkXb1UE6bFDx9ZLDUsom8+GKH
EglSFLjWAya+/Yu67nlSM5iJT2jTjKS2ewqnY2ASR8gsuWVFEhzerFb+hBoR8Ji1
9AAfAgR9Co1Vp/jsEidZ8umP
-----END PRIVATE KEY-----"
        certificate: "-----BEGIN CERTIFICATE-----
MIIDvTCCAqWgAwIBAgIJALwJNIgx3iQ4MA0GCSqGSIb3DQEBCwUAMHUxCzAJBgNV
BAYTAk1PMQswCQYDVQQIDAJNTzELMAkGA1UEBwwCTU8xEzARBgNVBAoMCmdhbWVz
b3VyY2UxEzARBgNVBAsMCmdhbWVzb3VyY2UxIjAgBgkqhkiG9w0BCQEWE2luZm9A
Z2FtZXNvdXJjZS5jb20wHhcNMjEwNzA4MTAyMTUwWhcNMzEwNzA2MTAyMTUwWjB1
MQswCQYDVQQGEwJNTzELMAkGA1UECAwCTU8xCzAJBgNVBAcMAk1PMRMwEQYDVQQK
DApnYW1lc291cmNlMRMwEQYDVQQLDApnYW1lc291cmNlMSIwIAYJKoZIhvcNAQkB
FhNpbmZvQGdhbWVzb3VyY2UuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEA1+4eIVyUjHsu0eselc1tK8O34CBI8uFN4R+QgGMA3aLagAg0PaW1DzJH
KC2tMZP373cq/1QYzVwQiP+RfaLsAOmpw2tPw+m8w9t61YOJQffAqWoWmmJZHd+Q
qSQ0IBkaSqN5MhcO3L/kxypn/qADI/uFttCuia5IgRymfBk1ij2XojOxvccQ1cVi
s59nTJ1+NX+LN4xkki5Sy1kiYj7qmSInlRs1b+sEOgWBUCVA/eziW1NaBGAituON
id8K4A0W1dI4s3EtP5MayyPllRvwA9m1WrEvrCTtW5taplhaIim+Udf9W8vYZMuw
F84pQbxMrlCiZVeQw3ed3vwhCpaRUQIDAQABo1AwTjAdBgNVHQ4EFgQUeJqa4QQI
/k3ARq1aajuMHE1OEYYwHwYDVR0jBBgwFoAUeJqa4QQI/k3ARq1aajuMHE1OEYYw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAQ17T/reA+jOXDDEa7fzK
rYMQ3kl41/FNRb5LSSNnkd0re1RjEkUcdp2IDWdddxVGAWNn23DRwskE2asdmEEs
RkxpLQCLNh0BXTgUjn3OdPxKYMY+KElkPTeyRIrfVNq3XU60W4tQP3DvH/YDpGwe
1H/Zn2LSw8kwFAjzyectjXONUXqKJ7FxvIuVw8fLL/PmMZqu2mYnA7ygw0jwPkTm
Qs+pqLmGxyEcZp8qntaak9KkmFw+mQgCwz8QUofXqqXbDSBnjTf7zUzO6Rs+2E7N
YOnaQ58bvBrQgf7/sxINcGcxNpUoIaBpOAQ6pqdWuu6QV1eV49xOgavLW47s4xjF
7Q==
-----END CERTIFICATE-----"
        digest_method: "XMLSecurity::Document::SHA256"
        signature_method: "XMLSecurity::Document::RSA_SHA256"
