development:
  laxino:
    auth_source:
      token: '10.10.5.46'
      type: 'Adfs'
    auth_source_detail:
      name: 'laxino_adfs'
      data:
        config_url: "https://fs.laxino.com/federationmetadata/2007-06/federationmetadata.xml"
        comparison: "minimum"
        private_key: "-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCeMSKCuiZddv1/
GwdlCQpUxVYbpWFXxuVpyC4AEWZMVeP46aWJUXn5WTJHq6BvQT8Y/9nTvh57Uzf1
tRbZsCpj+Kst4Hg1dSElaz3ytra+J9jz6lexxucqLKASlWSKFtlSsKcHCX73pOu2
HADcmNKRekLcWaT8yElXpVqBnhhOzanE1OQQtDwvK0+FY4Rcox8Kqcgb+O4R+qGO
lyWaG9/acLIw42xuDLK12+kzLLY0wTfeXcUPsP/zq598buGDQWbfXIrLMFwXIh9P
x5XO7nimvJPwiFyAXUS0ILVMhFeEwQXT5VgYkI4Z3WITjewUZhXVTPOx1lUmN+tW
KZpQ2OC/AgMBAAECggEAKUkJiLSsbpgvcIzNUUEawST/ZBe1YAM4vHLSDpJ78FA6
Pyw7V6s7+iedR7czF9YfcZbUcr6blfQSFr48SHQBnDW59y8uMEVxcSKb+ExXRSmB
JadzW6JdklQzMqZqpt9vuHUCIoQH7vnLyqtkTi5URkNyT6/Vr2NWQNmW1V09WtNI
/7UZxms0WyMi8AvS2iPhFR25mw0uq9CsQ0cFVeAN3IG7bnPYn8EcdhMjsYfHbYfO
qkiou1L6ALsAIofcCb2psPSKI/TFHyLIWzF4pcS+5mlc/b+c+1E1H9R7q1+iLj+9
YWXH+IwTjl2OhB1n87bkHklJv2KNfHxkv30F6OcjgQKBgQDLF26weGa8QNbx94BP
cDQZFFRGsNdTiOf+5P8Ozft+uvGyaB2PpR/fAXqjty5tgco0/aQ1+v//GkZk28nm
uIT3I1h425kta8Zj2f3kK6kAxKNFl9fsKXsF8IexL0VQIMuL+3n6iF5TcfVlT1oL
LfayJfv9eFW4lFxo1O7QiNpGCwKBgQDHZ0LbS5iIslkvDFl27gJfZEV60j5vS4mI
vWvlgwFuWH9b+tWP2+//LoTOomCTGMDyUpsZrYqbfsxuJt70TVhIuHNCqXC68aVg
9+px1Cnb0TY7UkYwtvDYu0/NwVuQKbzJGE/sy4aVQtSi8BZ7WHFtbQUqx5EuqiLa
7uIZ6sNEnQKBgQC7iDOpuEQFaUoRvJ06vT0eO2tmqzzp4e13rTToEsQ8TZuJRiKl
1bAMWG1KZ4fzjnmNXPkY72EbysNdtqZE6fW9z2GOmBhlnLNg2JZc7wPrtaeeR4wW
gmcbIPPrZN74EpBh/iCweuO+4efbWN6onBTEg9agQ1HEUxrRom2zGeuT6QKBgQCU
gCN7O65KR0BB2JmcB57+uadA0+ipbADuM9tx3oGnUwLuVjzL2Ui/qz4+wRDZG3s+
PCTEF8j9Co5mjk5GdH+GEM/N2nBY2POH5rnTseTGjuUrgpdBWky9q6nAGvr8vwiY
XqHPQLdm25GOEu07SN+YVbOea2eE8DHrCDKciIiJxQKBgQC1HFhlvAH8kvhihVj1
wGdfuFBo+AEfLl+MnnsHNx0uigMUPolddt+5CmQasttMKV+4IHSmDwlG0bMpAV9H
6+fX5TLYZgkrJaKKowQ1PUBUW1XMS6GpIlsOuzzTaxSJi00wQEDJ/rXWDx4eBj5l
RevUD6glxmm8ToJ+vkBXQiGjvQ==
-----END PRIVATE KEY-----"
        certificate: "-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIJAO81fl9gp0vPMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTcwNjEzMDQzODA5WhcNMTkwNjEzMDQzODA5WjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAnjEigromXXb9fxsHZQkKVMVWG6VhV8blacguABFmTFXj+OmliVF5+Vky
R6ugb0E/GP/Z074ee1M39bUW2bAqY/irLeB4NXUhJWs98ra2vifY8+pXscbnKiyg
EpVkihbZUrCnBwl+96TrthwA3JjSkXpC3Fmk/MhJV6VagZ4YTs2pxNTkELQ8LytP
hWOEXKMfCqnIG/juEfqhjpclmhvf2nCyMONsbgyytdvpMyy2NME33l3FD7D/86uf
fG7hg0Fm31yKyzBcFyIfT8eVzu54pryT8IhcgF1EtCC1TIRXhMEF0+VYGJCOGd1i
E43sFGYV1UzzsdZVJjfrVimaUNjgvwIDAQABo1AwTjAdBgNVHQ4EFgQUg0gu4ij9
VguxRGzihuguI2EqlUIwHwYDVR0jBBgwFoAUg0gu4ij9VguxRGzihuguI2EqlUIw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAIwsdxd1j3AzDKE4kdZhH
WS72ETLP7Wt8UIBKpSOKD+T983dAkum36svkYAB+y+UWeX4nDb/kTc+vibmn9lPm
Sq9amuy/wkKR6GVepVlIXR4KX6PDob08B/NiXMdWJMv6T/txO25tqdm5lCYjSlt+
nzeOETfak/W81RS7uzypyLbf7BLWw9JxqXilFrDLrIvWfZNb0Or9wFUYao9a2XPQ
lS7TfOaVuy26NXRJEndTEd+UAhRmXroi54B8/WO57WPES9WMp29pqEksiKaWxkh/
Synm9GOf+vrb2y4tSRmvboORYVAQaQT8FkTz39ul0cZMafkZ0wJQVuf97ISXQ9jU
Xg==
-----END CERTIFICATE-----"
        digest_method: "XMLSecurity::Document::SHA256"
        signature_method: "XMLSecurity::Document::RSA_SHA256"

integration0:
  laxino:
    auth_source:
      token: '127.0.0.1'
      type: 'Adfs'
    auth_source_detail:
      name: 'laxino_adfs'
      data:
        config_url: "https://fs.laxino.com/federationmetadata/2007-06/federationmetadata.xml"
        comparison: "minimum"
        private_key: "-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCeMSKCuiZddv1/
GwdlCQpUxVYbpWFXxuVpyC4AEWZMVeP46aWJUXn5WTJHq6BvQT8Y/9nTvh57Uzf1
tRbZsCpj+Kst4Hg1dSElaz3ytra+J9jz6lexxucqLKASlWSKFtlSsKcHCX73pOu2
HADcmNKRekLcWaT8yElXpVqBnhhOzanE1OQQtDwvK0+FY4Rcox8Kqcgb+O4R+qGO
lyWaG9/acLIw42xuDLK12+kzLLY0wTfeXcUPsP/zq598buGDQWbfXIrLMFwXIh9P
x5XO7nimvJPwiFyAXUS0ILVMhFeEwQXT5VgYkI4Z3WITjewUZhXVTPOx1lUmN+tW
KZpQ2OC/AgMBAAECggEAKUkJiLSsbpgvcIzNUUEawST/ZBe1YAM4vHLSDpJ78FA6
Pyw7V6s7+iedR7czF9YfcZbUcr6blfQSFr48SHQBnDW59y8uMEVxcSKb+ExXRSmB
JadzW6JdklQzMqZqpt9vuHUCIoQH7vnLyqtkTi5URkNyT6/Vr2NWQNmW1V09WtNI
/7UZxms0WyMi8AvS2iPhFR25mw0uq9CsQ0cFVeAN3IG7bnPYn8EcdhMjsYfHbYfO
qkiou1L6ALsAIofcCb2psPSKI/TFHyLIWzF4pcS+5mlc/b+c+1E1H9R7q1+iLj+9
YWXH+IwTjl2OhB1n87bkHklJv2KNfHxkv30F6OcjgQKBgQDLF26weGa8QNbx94BP
cDQZFFRGsNdTiOf+5P8Ozft+uvGyaB2PpR/fAXqjty5tgco0/aQ1+v//GkZk28nm
uIT3I1h425kta8Zj2f3kK6kAxKNFl9fsKXsF8IexL0VQIMuL+3n6iF5TcfVlT1oL
LfayJfv9eFW4lFxo1O7QiNpGCwKBgQDHZ0LbS5iIslkvDFl27gJfZEV60j5vS4mI
vWvlgwFuWH9b+tWP2+//LoTOomCTGMDyUpsZrYqbfsxuJt70TVhIuHNCqXC68aVg
9+px1Cnb0TY7UkYwtvDYu0/NwVuQKbzJGE/sy4aVQtSi8BZ7WHFtbQUqx5EuqiLa
7uIZ6sNEnQKBgQC7iDOpuEQFaUoRvJ06vT0eO2tmqzzp4e13rTToEsQ8TZuJRiKl
1bAMWG1KZ4fzjnmNXPkY72EbysNdtqZE6fW9z2GOmBhlnLNg2JZc7wPrtaeeR4wW
gmcbIPPrZN74EpBh/iCweuO+4efbWN6onBTEg9agQ1HEUxrRom2zGeuT6QKBgQCU
gCN7O65KR0BB2JmcB57+uadA0+ipbADuM9tx3oGnUwLuVjzL2Ui/qz4+wRDZG3s+
PCTEF8j9Co5mjk5GdH+GEM/N2nBY2POH5rnTseTGjuUrgpdBWky9q6nAGvr8vwiY
XqHPQLdm25GOEu07SN+YVbOea2eE8DHrCDKciIiJxQKBgQC1HFhlvAH8kvhihVj1
wGdfuFBo+AEfLl+MnnsHNx0uigMUPolddt+5CmQasttMKV+4IHSmDwlG0bMpAV9H
6+fX5TLYZgkrJaKKowQ1PUBUW1XMS6GpIlsOuzzTaxSJi00wQEDJ/rXWDx4eBj5l
RevUD6glxmm8ToJ+vkBXQiGjvQ==
-----END PRIVATE KEY-----"
        certificate: "-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIJAO81fl9gp0vPMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTcwNjEzMDQzODA5WhcNMTkwNjEzMDQzODA5WjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAnjEigromXXb9fxsHZQkKVMVWG6VhV8blacguABFmTFXj+OmliVF5+Vky
R6ugb0E/GP/Z074ee1M39bUW2bAqY/irLeB4NXUhJWs98ra2vifY8+pXscbnKiyg
EpVkihbZUrCnBwl+96TrthwA3JjSkXpC3Fmk/MhJV6VagZ4YTs2pxNTkELQ8LytP
hWOEXKMfCqnIG/juEfqhjpclmhvf2nCyMONsbgyytdvpMyy2NME33l3FD7D/86uf
fG7hg0Fm31yKyzBcFyIfT8eVzu54pryT8IhcgF1EtCC1TIRXhMEF0+VYGJCOGd1i
E43sFGYV1UzzsdZVJjfrVimaUNjgvwIDAQABo1AwTjAdBgNVHQ4EFgQUg0gu4ij9
VguxRGzihuguI2EqlUIwHwYDVR0jBBgwFoAUg0gu4ij9VguxRGzihuguI2EqlUIw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAIwsdxd1j3AzDKE4kdZhH
WS72ETLP7Wt8UIBKpSOKD+T983dAkum36svkYAB+y+UWeX4nDb/kTc+vibmn9lPm
Sq9amuy/wkKR6GVepVlIXR4KX6PDob08B/NiXMdWJMv6T/txO25tqdm5lCYjSlt+
nzeOETfak/W81RS7uzypyLbf7BLWw9JxqXilFrDLrIvWfZNb0Or9wFUYao9a2XPQ
lS7TfOaVuy26NXRJEndTEd+UAhRmXroi54B8/WO57WPES9WMp29pqEksiKaWxkh/
Synm9GOf+vrb2y4tSRmvboORYVAQaQT8FkTz39ul0cZMafkZ0wJQVuf97ISXQ9jU
Xg==
-----END CERTIFICATE-----"
        digest_method: "XMLSecurity::Document::SHA256"
        signature_method: "XMLSecurity::Document::RSA_SHA256"

staging0:
  laxino:
    auth_source:
      token: '10.10.45.250'
      type: 'Adfs'
    auth_source_detail:
      name: 'laxino_adfs'
      data:
        config_url: "https://fs.laxino.com/federationmetadata/2007-06/federationmetadata.xml"
        comparison: "minimum"
        private_key: "-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCeMSKCuiZddv1/
GwdlCQpUxVYbpWFXxuVpyC4AEWZMVeP46aWJUXn5WTJHq6BvQT8Y/9nTvh57Uzf1
tRbZsCpj+Kst4Hg1dSElaz3ytra+J9jz6lexxucqLKASlWSKFtlSsKcHCX73pOu2
HADcmNKRekLcWaT8yElXpVqBnhhOzanE1OQQtDwvK0+FY4Rcox8Kqcgb+O4R+qGO
lyWaG9/acLIw42xuDLK12+kzLLY0wTfeXcUPsP/zq598buGDQWbfXIrLMFwXIh9P
x5XO7nimvJPwiFyAXUS0ILVMhFeEwQXT5VgYkI4Z3WITjewUZhXVTPOx1lUmN+tW
KZpQ2OC/AgMBAAECggEAKUkJiLSsbpgvcIzNUUEawST/ZBe1YAM4vHLSDpJ78FA6
Pyw7V6s7+iedR7czF9YfcZbUcr6blfQSFr48SHQBnDW59y8uMEVxcSKb+ExXRSmB
JadzW6JdklQzMqZqpt9vuHUCIoQH7vnLyqtkTi5URkNyT6/Vr2NWQNmW1V09WtNI
/7UZxms0WyMi8AvS2iPhFR25mw0uq9CsQ0cFVeAN3IG7bnPYn8EcdhMjsYfHbYfO
qkiou1L6ALsAIofcCb2psPSKI/TFHyLIWzF4pcS+5mlc/b+c+1E1H9R7q1+iLj+9
YWXH+IwTjl2OhB1n87bkHklJv2KNfHxkv30F6OcjgQKBgQDLF26weGa8QNbx94BP
cDQZFFRGsNdTiOf+5P8Ozft+uvGyaB2PpR/fAXqjty5tgco0/aQ1+v//GkZk28nm
uIT3I1h425kta8Zj2f3kK6kAxKNFl9fsKXsF8IexL0VQIMuL+3n6iF5TcfVlT1oL
LfayJfv9eFW4lFxo1O7QiNpGCwKBgQDHZ0LbS5iIslkvDFl27gJfZEV60j5vS4mI
vWvlgwFuWH9b+tWP2+//LoTOomCTGMDyUpsZrYqbfsxuJt70TVhIuHNCqXC68aVg
9+px1Cnb0TY7UkYwtvDYu0/NwVuQKbzJGE/sy4aVQtSi8BZ7WHFtbQUqx5EuqiLa
7uIZ6sNEnQKBgQC7iDOpuEQFaUoRvJ06vT0eO2tmqzzp4e13rTToEsQ8TZuJRiKl
1bAMWG1KZ4fzjnmNXPkY72EbysNdtqZE6fW9z2GOmBhlnLNg2JZc7wPrtaeeR4wW
gmcbIPPrZN74EpBh/iCweuO+4efbWN6onBTEg9agQ1HEUxrRom2zGeuT6QKBgQCU
gCN7O65KR0BB2JmcB57+uadA0+ipbADuM9tx3oGnUwLuVjzL2Ui/qz4+wRDZG3s+
PCTEF8j9Co5mjk5GdH+GEM/N2nBY2POH5rnTseTGjuUrgpdBWky9q6nAGvr8vwiY
XqHPQLdm25GOEu07SN+YVbOea2eE8DHrCDKciIiJxQKBgQC1HFhlvAH8kvhihVj1
wGdfuFBo+AEfLl+MnnsHNx0uigMUPolddt+5CmQasttMKV+4IHSmDwlG0bMpAV9H
6+fX5TLYZgkrJaKKowQ1PUBUW1XMS6GpIlsOuzzTaxSJi00wQEDJ/rXWDx4eBj5l
RevUD6glxmm8ToJ+vkBXQiGjvQ==
-----END PRIVATE KEY-----"
        certificate: "-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIJAO81fl9gp0vPMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTcwNjEzMDQzODA5WhcNMTkwNjEzMDQzODA5WjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAnjEigromXXb9fxsHZQkKVMVWG6VhV8blacguABFmTFXj+OmliVF5+Vky
R6ugb0E/GP/Z074ee1M39bUW2bAqY/irLeB4NXUhJWs98ra2vifY8+pXscbnKiyg
EpVkihbZUrCnBwl+96TrthwA3JjSkXpC3Fmk/MhJV6VagZ4YTs2pxNTkELQ8LytP
hWOEXKMfCqnIG/juEfqhjpclmhvf2nCyMONsbgyytdvpMyy2NME33l3FD7D/86uf
fG7hg0Fm31yKyzBcFyIfT8eVzu54pryT8IhcgF1EtCC1TIRXhMEF0+VYGJCOGd1i
E43sFGYV1UzzsdZVJjfrVimaUNjgvwIDAQABo1AwTjAdBgNVHQ4EFgQUg0gu4ij9
VguxRGzihuguI2EqlUIwHwYDVR0jBBgwFoAUg0gu4ij9VguxRGzihuguI2EqlUIw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAIwsdxd1j3AzDKE4kdZhH
WS72ETLP7Wt8UIBKpSOKD+T983dAkum36svkYAB+y+UWeX4nDb/kTc+vibmn9lPm
Sq9amuy/wkKR6GVepVlIXR4KX6PDob08B/NiXMdWJMv6T/txO25tqdm5lCYjSlt+
nzeOETfak/W81RS7uzypyLbf7BLWw9JxqXilFrDLrIvWfZNb0Or9wFUYao9a2XPQ
lS7TfOaVuy26NXRJEndTEd+UAhRmXroi54B8/WO57WPES9WMp29pqEksiKaWxkh/
Synm9GOf+vrb2y4tSRmvboORYVAQaQT8FkTz39ul0cZMafkZ0wJQVuf97ISXQ9jU
Xg==
-----END CERTIFICATE-----"
        digest_method: "XMLSecurity::Document::SHA256"
        signature_method: "XMLSecurity::Document::RSA_SHA256"
