audit_target:
  system_user:
    locale_key: "user.system_user"
    action_name:
      edit_role:
        action_type: "update"
        locale_key: "user.edit_role"
      create:
        action_type: "create"
        locale_key: "user.create_system_user"
  domain:
    locale_key: "domain.name"
    action_name:
      create:
        action_type: "create"
        locale_key: "domain.create"
  domain_casino:
    locale_key: "domain_casino.name"
    action_name:
      create:
        action_type: "create"
        locale_key: "domain_casino.create"
      inactive:
        action_type: "inactive"
        locale_key: "domain_casino.inactive"