default: &default
  user_management: 'https://int-sso.laxino.com/home'
  gaming_operation: 'https://int-ap.laxino.com/home'
  cage: 'https://int-cage.laxino.com/home'
  station_management: 'https://int-sm.laxino.com/index'
  game_recall: 'https://int-grms.laxino.com'
  signature_verifier: 'https://int-sv.laxino.com/index'
  audit_portal: 'https://int-audp.laxino.com/index'
  asset_management: 'https://int-dam.laxino.com/index'
  trade_promotion: 'https://int-tp.laxino.com/index'
  master_data_service: 'https://int-nmds.laxino.com/dashboard'

test:
  <<: *default

development:
  <<: *default

integration0:
  user_management: 'https://int-sso.laxino.com/home'
  gaming_operation: 'https://int-ap.laxino.com/home'
  cage: 'https://int-cms.laxino.com/home'
  station_management: 'https://int-sm.laxino.com/index'
  game_recall: 'https://int-gr.laxino.com/search_game_history'
  signature_verifier: 'https://int-sv.laxino.com/index'
  audit_portal: 'https://int-audp.laxino.com/index'
  asset_management: 'https://int-dam.laxino.com/index'
  trade_promotion: 'https://int-tp.laxino.com/index'

staging0:
  user_management: 'https://stg-sso.laxino.com/home'
  gaming_operation: 'https://stg-ap.laxino.com/home'
  cage: 'https://stg-cms.laxino.com/home'
  station_management: 'https://stg-sm.laxino.com/index'
  game_recall: 'https://stg-gr.laxino.com/search_game_history'
  signature_verifier: 'https://stg-sv.laxino.com/index'
  audit_portal: 'https://stg-audp.laxino.com/index'
  asset_management: 'https://stg-dam.laxino.com/index'
  trade_promotion: 'https://stg-tp.laxino.com/index'

staging1:
  user_management: 'https://stg1-sso.laxino.com/home'
  gaming_operation: 'https://stg1-ap.laxino.com/home'
  cage: 'https://stg1-cms.laxino.com/home'
  station_management: 'https://stg1-sm.laxino.com/index'
  signature_verifier: 'https://stg1-sv.laxino.com/index'
  audit_portal: 'https://stg1-audp.laxino.com/index'
  asset_management: 'https://stg1-dam.laxino.com/index'
  trade_promotion: 'https://stg1-tp.laxino.com/index'

sandbox2:
  user_management: 'https://snd-sso.777iportal.com/home'
  gaming_operation: 'https://snd-ap.777iportal.com/home'
  game_recall: 'https://snd-gr.777iportal.com/search_game_history'
  trade_promotion: 'https://snd-tp.777iportal.com/index'

smartocean2:
  user_management: 'https://sso.777iportal.com/home'
  gaming_operation: 'https://ap.777iportal.com/home'
  game_recall: 'https://gr.777iportal.com/search_game_history'
  trade_promotion: 'https://tp.777iportal.com/index'

sandbox0:
  user_management: 'https://snd-sso.888iportal.com/home'
  gaming_operation: 'https://snd-ap.888iportal.com/home'
  game_recall: 'https://snd-gr.888iportal.com/search_game_history'
  trade_promotion: 'https://snd-tp.888iportal.com/index'

production0:
  user_management: 'https://sso.888iportal.com/home'
  gaming_operation: 'https://ap.888iportal.com/home'
  game_recall: 'https://gr.888iportal.com/search_game_history'
  trade_promotion: 'https://tp.888iportal.com/index'

sandbox3:
  user_management: 'https://snd-sso.138777.net/home'
  gaming_operation: 'https://snd-ap.138777.net/home'
  cage: 'https://snd-cms.138777.net/home'
  station_management: 'https://snd-sm.138777.net/index'
  game_recall: 'https://snd-gr.138777.net/search_game_history'
  signature_verifier: 'https://snd-sv.138777.net/index'
  audit_portal: 'https://snd-audp.138777.net/index'
  report_portal: 'https://snd-report.138777.net/Reports/Pages/Folder.aspx'

production3:
  user_management: 'https://sso.gogamesource.com/home'
  gaming_operation: 'https://ap.gogamesource.com/home'
  cage: 'https://cms.gogamesource.com/home'
  station_management: 'https://sm.gogamesource.com/index'
  game_recall: 'https://gr.gogamesource.com/search_game_history'
  signature_verifier: 'https://sv.gogamesource.com/index'
  audit_portal: 'https://audp.gogamesource.com/index'
  asset_management: 'https://dam.gogamesource.com/index'

production4:
  user_management: 'https://sso.laxino.com/home'
  asset_management: 'https://dam.laxino.com/index'
  master_data_service: 'https://nmds.laxino.com/dashboard'

sandbox:
  user_management: 'https://cert-sso.gogamesource.com/home'
  gaming_operation: 'https://cert-ap.gogamesource.com/home'
  cage: 'https://cert-cms.gogamesource.com/home'
  station_management: 'https://cert-sm.gogamesource.com/index'
  game_recall: 'https://cert-gr.gogamesource.com/search_game_history'
  signature_verifier: 'https://cert-sv.gogamesource.com/index'
  audit_portal: 'https://cert-audp.gogamesource.com/index'
  report_portal: 'https://cert-report.gogamesource.com/Reports/Pages/Folder.aspx'

production:
  user_management: 'https://sso.gogamesource.com/home'
  asset_management: 'https://dam.gogamesource.com/index'
  master_data_service: 'https://nmds.gogamesource.com/dashboard'

ias_prd:
  user_management: 'https://sso.cert.laxino.com//home'
  gaming_operation: 'https://ap.cert.laxino.com/home'
  cage: 'https://cms.cert.laxino.com/home'
  station_management: 'https://mtm.cert.laxino.com/index'
  signature_verifier: 'https://sv.cert.laxino.com/index'
  audit_portal: 'https://audp.cert.laxino.com/index'
  asset_management: 'https://dam.cert.laxino.com/index'
  marketing_portal: 'https://mp.cert.laxino.com/home'
  platform_game_recall: 'https://ogr.cert.laxino.com'

sandbox5:
  user_management: 'https://snd5-sso.8888pgy3c.com/home'
  gaming_operation: 'https://snd5-ap.8888pgy3c.com/home'
  cage: 'https://snd5-cms.8888pgy3c.com/home'
  station_management: 'https://snd5-mtm.8888pgy3c.com/index'
  signature_verifier: 'https://snd5-sv.8888pgy3c.com/index'
  audit_portal: 'https://snd5-audp.8888pgy3c.com/index'
  marketing_portal: 'https://snd5-mp.8888pgy3c.com/home'
  platform_game_recall: 'https://snd5-ogr.8888pgy3c.com'
  report_portal: 'https://snd5-report.8888pgy3c.com/Reports/Pages/Folder.aspx'

sandbox6:
  user_management: 'https://snd6-sso.138777.net/home'
  cage: 'https://snd6-cms.138777.net/home'
  station_management: 'https://snd6-mtm.138777.net/index'
  audit_portal: 'https://snd6-audp.138777.net/index'
  marketing_portal: 'https://snd6-mp.138777.net/home'
  platform_game_recall: 'https://snd6-ogr.138777.net'
  report_portal: 'https://snd6-report.138777.net/Reports/Pages/Folder.aspx'
  platform_gaming_operation: 'https://snd6-go.138777.net'
  signature_verifier_portal: 'https://snd6-sv.138777.net'
  signature_management: 'https://snd6-spp.138777.net'
  kiosk_management: 'https://snd6-kosp.138777.net'
  spindle: 'https://snd6-lmp.138777.net'

cert1:
  user_management: 'https://cert1-sso.cert.laxino.com/home'
  cage: 'https://cert1-cms.cert.laxino.com/home'
  station_management: 'https://cert1-mtm.cert.laxino.com/index'
  audit_portal: 'https://cert1-audp.cert.laxino.com/index'
  marketing_portal: 'https://cert1-mp.cert.laxino.com/home'
  platform_game_recall: 'https://cert1-ogr.cert.laxino.com'
  report_portal: 'https://cert1-report.cert.laxino.com/Reports/Pages/Folder.aspx'
  platform_gaming_operation: 'https://cert1-go.cert.laxino.com'
  signature_verifier_portal: 'https://cert1-sv.cert.laxino.com'
  signature_management: 'https://cert1-spp.cert.laxino.com'
  kiosk_management: 'https://cert1-kosp.cert.laxino.com'
  spindle: 'https://cert1-lmp.cert.laxino.com'

ga0:
  user_management: 'https://ga0-sso.laxino.com/home'
  signature_management: 'https://ga0-spp.laxino.com'

production6:
  user_management: 'https://prd6-sso.gogamesource.com/home'
  cage: 'https://prd6-cms.gogamesource.com/home'
  station_management: 'https://prd6-mtm.gogamesource.com/index'
  audit_portal: 'https://prd6-audp.gogamesource.com/index'
  marketing_portal: 'https://prd6-mp.gogamesource.com/home'
  platform_game_recall: 'https://prd6-ogr.gogamesource.com'
  report_portal: 'https://prd6-report.gogamesource.com/Reports/Pages/Folder.aspx'
  platform_gaming_operation: 'https://prd6-go.gogamesource.com'
  signature_verifier_portal: 'https://prd6-sv.gogamesource.com'
  signature_management: 'https://prd6-spp.gogamesource.com'
  kiosk_management: 'https://prd6-kosp.gogamesource.com'
  spindle: 'https://prd6-lmp.gogamesource.com'

sandbox8:
  user_management: 'https://snd8-sso.grac381.com/home'
  cage: 'https://snd8-cms.grac381.com/home'
  station_management: 'https://snd8-mtm.grac381.com/index'
  audit_portal: 'https://snd8-audp.grac381.com/index'
  marketing_portal: 'https://snd8-mp.grac381.com/home'
  platform_game_recall: 'https://snd8-ogr.grac381.com'
  report_portal: 'https://snd8-report.grac381.com/Reports/Pages/Folder.aspx'
  platform_gaming_operation: 'https://snd8-go.grac381.com'
  signature_verifier_portal: 'https://snd8-sv.grac381.com'
  signature_management: 'https://snd8-spp.grac381.com'
  kiosk_management: 'https://snd8-kosp.grac381.com'
  spindle: 'https://snd8-lmp.grac381.com'

sandbox10:
  user_management: 'https://snd10-sso.gogamesource.com.ph/home'
  cage: 'https://snd10-cms.gogamesource.com.ph/home'
  station_management: 'https://snd10-mtm.gogamesource.com.ph/index'
  audit_portal: 'https://snd10-audp.gogamesource.com.ph/index'
  marketing_portal: 'https://snd10-mp.gogamesource.com.ph/home'
  platform_game_recall: 'https://snd10-ogr.gogamesource.com.ph'
  report_portal: 'https://snd10-report.gogamesource.com.ph/Reports/Pages/Folder.aspx'
  platform_gaming_operation: 'https://snd10-go.gogamesource.com.ph'
  signature_verifier_portal: 'https://snd10-sv.gogamesource.com.ph'
  signature_management: 'https://snd10-spp.gogamesource.com.ph'
  kiosk_management: 'https://snd10-kosp.gogamesource.com.ph'
  spindle: 'https://snd10-lmp.gogamesource.com.ph'
  player_approval_operations_portal: 'https://snd10-paop.gogamesource.com.ph'

production10:
  user_management: 'https://prd10-sso.gogamesource.com.ph/home'
  cage: 'https://prd10-cms.gogamesource.com.ph/home'
  station_management: 'https://prd10-mtm.gogamesource.com.ph/index'
  audit_portal: 'https://prd10-audp.gogamesource.com.ph/index'
  marketing_portal: 'https://prd10-mp.gogamesource.com.ph/home'
  platform_game_recall: 'https://prd10-ogr.gogamesource.com.ph'
  report_portal: 'https://prd10-report.gogamesource.com.ph/Reports/Pages/Folder.aspx'
  platform_gaming_operation: 'https://prd10-go.gogamesource.com.ph'
  signature_verifier_portal: 'https://prd10-sv.gogamesource.com.ph'
  kiosk_management: 'https://prd10-kosp.gogamesource.com.ph'
  spindle: 'https://prd10-lmp.gogamesource.com.ph'

sandbox9:
  user_management: 'https://snd9-sso.grac381.com/home'
  station_management: 'https://snd9-mtm.grac381.com/index'
