default: &default
  user_management: 'https://int-sso.laxino.com'
  gaming_operation: 'https://int-ap.laxino.com'
  cage: 'https://int-cage.laxino.com'
  station_management: 'https://int-sm.laxino.com'
  game_recall: 'https://int-grms.laxino.com'
  signature_verifier: 'https://int-sv.laxino.com'
  audit_portal: 'https://int-audp.laxino.com'
  asset_management: 'https://int-dam.laxino.com'
  trade_promotion: 'https://int-tpms.laxino.com'
  master_data_service: 'https://int-mds.laxino.com'

test:
  <<: *default

development:
  <<: *default

integration0:
  <<: *default

staging0:
  user_management: 'https://stg-sso2.laxino.com/home'
  gaming_operation: 'https://stg-ap2.laxino.com/home'
  cage: 'https://stg-cms2.laxino.com/home'
  station_management: 'https://stg-sm2.laxino.com/index'
  game_recall: 'https://stg-gr2.laxino.com/search_game_history'
  signature_verifier: 'https://stg-sv2.laxino.com/index'
  audit_portal: 'https://stg-audp2.laxino.com/index'
  asset_management: 'https://stg-dam2.laxino.com/index'
  trade_promotion: 'https://stg-tpms2.laxino.com/index'

sandbox3:
  user_management: 'https://snd-sso.138777.net/home'
  gaming_operation: 'https://snd-ap.138777.net/home'
  cage: 'https://snd-cms.138777.net/home'
  station_management: 'https://snd-sm.138777.net/index'
  game_recall: 'https://snd-gr.138777.net/search_game_history'
  signature_verifier: 'https://snd-sv.138777.net/index'
  audit_portal: 'https://snd-audp.138777.net/index'

production3:
  user_management: 'https://sso.pia.com.mo/home'
  gaming_operation: 'https://ap.pia.com.mo/home'
  cage: 'https://cms.pia.com.mo/home'
  station_management: 'https://sm.pia.com.mo/index'
  game_recall: 'https://gr.pia.com.mo/search_game_history'
  signature_verifier: 'https://sv.pia.com.mo/index'
  audit_portal: 'https://audp.pia.com.mo/index'
  asset_management: 'https://dam.pia.com.mo/index'
