default: &default
  user_management: 'https://int-sso.laxino.com/home'
  gaming_operation: 'https://int-ap.laxino.com/home'
  cage: 'https://int-cage.laxino.com/home'
  station_management: 'https://int-sm.laxino.com/index'
  game_recall: 'https://int-grms.laxino.com'
  signature_verifier: 'https://int-sv.laxino.com/index'
  audit_portal: 'https://int-audp.laxino.com/index'
  asset_management: 'https://int-dam.laxino.com/index'
  trade_promotion: 'https://int-tpms.laxino.com/index'
  master_data_service: 'https://int-nmds.laxino.com/dashboard'

test:
  <<: *default

development:
  <<: *default

integration0:
  user_management: 'https://int-sso.laxino.com/home'
  gaming_operation: 'https://int-ap.laxino.com/home'
  cage: 'https://int-cms.laxino.com/home'
  station_management: 'https://int-sm.laxino.com/index'
  game_recall: 'https://int-gr.laxino.com/search_game_history'
  signature_verifier: 'https://int-sv.laxino.com/index'
  audit_portal: 'https://int-audp.laxino.com/index'
  asset_management: 'https://int-dam.laxino.com/index'
  trade_promotion: 'https://int-tpms.laxino.com/index'

staging0:
  user_management: 'https://stg-sso.laxino.com/home'
  gaming_operation: 'https://stg-ap.laxino.com/home'
  cage: 'https://stg-cms.laxino.com/home'
  station_management: 'https://stg-sm.laxino.com/index'
  game_recall: 'https://stg-gr.laxino.com/search_game_history'
  signature_verifier: 'https://stg-sv.laxino.com/index'
  audit_portal: 'https://stg-audp.laxino.com/index'
  asset_management: 'https://stg-dam.laxino.com/index'
  trade_promotion: 'https://stg-tpms.laxino.com/index'

sandbox2:
  user_management: 'https://snd-sso.777iportal.com/home'
  gaming_operation: 'https://snd-ap.777iportal.com/home'
  game_recall: 'https://snd-gr.777iportal.com/search_game_history'
  trade_promotion: 'https://snd-tpms.777iportal.com/index'

smartocean2:
  user_management: 'https://sso.777iportal.com/home'
  gaming_operation: 'https://ap.777iportal.com/home'
  game_recall: 'https://gr.777iportal.com/search_game_history'
  trade_promotion: 'https://tpms.777iportal.com/index'

sandbox0:
  user_management: 'https://snd-sso.888iportal.com/home'
  gaming_operation: 'https://snd-ap.888iportal.com/home'
  game_recall: 'https://snd-gr.888iportal.com/search_game_history'
  trade_promotion: 'https://snd-tpms.888iportal.com/index'

production0:
  user_management: 'https://sso.888iportal.com/home'
  gaming_operation: 'https://ap.888iportal.com/home'
  game_recall: 'https://gr.888iportal.com/search_game_history'
  trade_promotion: 'https://tpms.888iportal.com/index'

sandbox3:
  user_management: 'https://snd-sso.138777.net/home'
  gaming_operation: 'https://snd-ap.138777.net/home'
  cage: 'https://snd-cms.138777.net/home'
  station_management: 'https://snd-sm.138777.net/index'
  game_recall: 'https://snd-gr.138777.net/search_game_history'
  signature_verifier: 'https://snd-sv.138777.net/index'
  audit_portal: 'https://snd-audp.138777.net/index'
  report_portal: 'https://snd-report.138777.net/Reports/Pages/Folder.aspx'

production3:
  user_management: 'https://sso.pia.com.mo/home'
  gaming_operation: 'https://ap.pia.com.mo/home'
  cage: 'https://cms.pia.com.mo/home'
  station_management: 'https://sm.pia.com.mo/index'
  game_recall: 'https://gr.pia.com.mo/search_game_history'
  signature_verifier: 'https://sv.pia.com.mo/index'
  audit_portal: 'https://audp.pia.com.mo/index'
  asset_management: 'https://dam.pia.com.mo/index'

production4:
  user_management: 'https://sso.laxino.com/home'
  asset_management: 'https://dam.laxino.com/index'
  master_data_service: 'https://nmds.laxino.com/dashboard'

sandbox:
  user_management: 'https://cert-sso.gogamesource.com/home'
  gaming_operation: 'https://cert-ap.gogamesource.com/home'
  cage: 'https://cert-cms.gogamesource.com/home'
  station_management: 'https://cert-sm.gogamesource.com/index'
  game_recall: 'https://cert-gr.gogamesource.com/search_game_history'
  signature_verifier: 'https://cert-sv.gogamesource.com/index'
  audit_portal: 'https://cert-audp.gogamesource.com/index'
  report_portal: 'https://cert-report.gogamesource.com/Reports/Pages/Folder.aspx'

production:
  user_management: 'https://sso.gogamesource.com/home'
  asset_management: 'https://dam.gogamesource.com/index'
  master_data_service: 'https://nmds.gogamesource.com/dashboard'
