#
# set your custom CONSTANT here. All elements defined here will become a constant with uppercase
# example:
#
# development:
#   app_name: 'user_management'
#
# APP_NAME #=> 'user_management'
#
default: &default
  app_name: 'user_management'
  ssrs_app_name: 'report_portal'
  default_timezone: 'UTC'
  search_day_range: 7
  search_range_for_audit_log: 7
  search_range_for_login_history: 7
  admin_casino_id: 1000
  admin_role_type_name: 'internal'
  remain_login_history_days: 100
  url_base: 'https://test-sso.laxino.com'

test:
  <<: *default

development:
  <<: *default
  url_base: 'http://10.10.5.169:3000'

integration0:
  <<: *default
  url_base: 'https://int-sso.laxino.com'

staging0:
  <<: *default
  # url_base: 'https://stg-sso2.laxino.com'
  url_base: 'https://stg-sso.laxino.com'

staging1:
  <<: *default
  url_base: 'https://stg1-sso.laxino.com'

sandbox0:
  <<: *default
  url_base: 'https://snd-sso.888iportal.com'

production0:
  <<: *default
  url_base: 'https://sso.888iportal.com'

mockup0:
  <<: *default

sandbox2:
  <<: *default
  url_base: 'https://snd-sso.777iportal.com'

smartocean2:
  <<: *default
  url_base: 'https://sso.777iportal.com'

sandbox3:
  <<: *default
  url_base: 'https://snd-sso.138777.net'
  remain_login_history_days: 455

production3:
  <<: *default
  url_base: 'https://sso.gogamesource.com'
  remain_login_history_days: 455

production4:
  <<: *default
  url_base: 'https://sso.laxino.com'

sandbox:
  <<: *default
  url_base: 'https://cert-sso.gogamesource.com'

production:
  <<: *default
  url_base: 'https://sso.gogamesource.com'

ias_prd:
  <<: *default
  url_base: 'https://sso.cert.laxino.com'
  remain_login_history_days: 455

sandbox5:
  <<: *default
  url_base: 'https://snd5-sso.8888pgy3c.com'
  remain_login_history_days: 455

sandbox6:
  <<: *default
  url_base: 'https://snd6-sso.138777.net'
  remain_login_history_days: 455

cert1:
  <<: *default
  url_base: 'https://cert1-sso.cert.laxino.com'
  remain_login_history_days: 455

ga0:
  <<: *default
  url_base: 'https://ga0-sso.laxino.com'

production6:
  <<: *default
  url_base: 'https://prd6-sso.gogamesource.com'
  remain_login_history_days: 455
