#
# set your custom CONSTANT here. All elements defined here will become a constant with uppercase
# example:
#
# development:
#   app_name: 'user_management'
#
# APP_NAME #=> 'user_management'
#
default: &default
  app_name: 'user_management'
  search_day_range: 7
  search_range_for_audit_log: 7
  search_range_for_login_history: 7
  admin_casino_id: 1000
  admin_role_type_name: 'internal'
  remain_login_history_days: 100

test:
  <<: *default

development:
  <<: *default

integration0:
  <<: *default
  site_domain: 'laxino.com'

staging0:
  <<: *default
  site_domain: 'laxino.com'

staging0_external:
  <<: *default
  site_domain: 'laxino.com'

sandbox0:
  <<: *default
  site_domain: 'laxigames.com'

production0:
  <<: *default
  site_domain: 'laxigames.com'

mockup0:
  <<: *default
  site_domain: 'laxino.com'

sandbox2:
  <<: *default
  site_domain: 'laxigames.local'

smartocean2:
  <<: *default
  site_domain: 'laxigames.local'

sandbox3:
  <<: *default
  site_domain: 'laxigames.local'

production3:
  <<: *default
  site_domain: 'laxigames.local'

production4:
  <<: *default
  site_domain: 'laxigames.local'
