#
# set your custom CONSTANT here. All elements defined here will become a constant with uppercase
# example:
#
# development:
#   app_name: 'user_management'
#
# APP_NAME #=> 'user_management'
#
default: &default
  app_name: 'user_management'
  ssrs_app_name: 'report_portal'
  search_day_range: 7
  search_range_for_audit_log: 7
  search_range_for_login_history: 7
  admin_casino_id: 1000
  admin_role_type_name: 'internal'
  remain_login_history_days: 100
  url_base: 'https://test-sso.laxino.com'

test:
  <<: *default

development:
  <<: *default

integration0:
  <<: *default
  site_domain: 'laxino.com'
  url_base: 'https://int-sso.laxino.com'

staging0:
  <<: *default
  site_domain: 'laxino.com'
  url_base: 'https://stg-sso.laxino.com'

staging0_external:
  <<: *default
  site_domain: 'laxino.com'

sandbox0:
  <<: *default
  site_domain: 'laxigames.com'
  url_base: 'https://snd-sso.888iportal.com'

production0:
  <<: *default
  site_domain: 'laxigames.com'
  url_base: 'https://sso.888iportal.com'

mockup0:
  <<: *default
  site_domain: 'laxino.com'

sandbox2:
  <<: *default
  site_domain: 'laxigames.local'
  url_base: 'https://snd-sso.777iportal.com'

smartocean2:
  <<: *default
  site_domain: 'laxigames.local'
  url_base: 'https://sso.777iportal.com'

sandbox3:
  <<: *default
  site_domain: 'laxigames.local'
  url_base: 'https://snd-sso.138777.net'
  remain_login_history_days: 455

production3:
  <<: *default
  site_domain: 'laxigames.local'
  url_base: 'https://sso.gogamesource.com'
  remain_login_history_days: 455

production4:
  <<: *default
  site_domain: 'laxigames.local'
  url_base: 'https://sso.laxino.com'

sandbox:
  <<: *default
  site_domain: 'laxigames.local'
  url_base: 'https://cert-sso.gogamesource.com'

production:
  <<: *default
  site_domain: 'laxigames.local'
  url_base: 'https://sso.gogamesource.com'
