development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_development
  username: rigi
  password: rigi
  host: mo-int-generic-db01.rnd.laxino.com
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_test
  username: rigi
  password: rigi
  host: mo-int-generic-db01.rnd.laxino.com
  port: 3306

integration0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_integration
  username: rigi
  password: rigi
  host: mo-int-generic-db01.rnd.laxino.com
  port: 3306

staging0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_staging
  username: rigi
  password: rigi
  host: mo-stg-generic-db01.rnd.laxino.com
  port: 3306

sandbox0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: ph-snd-sso-vdb01.laxigames.com
  port: 6034

production0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: ph-prd-sso-vdb01.laxigames.com
  port: 6033

sandbox2:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: tw-snd-sso-vdb01.laxigames.local  
  port: 6034

smartocean2:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: tw-prd-sso-vdb01.laxigames.local
  port: 6033
