development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_development2
  username: rigi
  password: rigi
  host: hq-int-sso-vdb01.laxino.local
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_test
  username: rigi
  password: rigi
  host: hq-int-sso-vdb01.laxino.local
  port: 3306

integration0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_integration
  username: rigi
  password: rigi
  host: hq-int-sso-vdb01.laxino.local
  port: 3306

integration1:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_integration
  username: rigi
  password: rigi
  host: sso-vdb01.int1.ias.local
  port: 3306

staging0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_staging
  username: rigi
  password: rigi
  # host: mo-stg-sso-vdb01.rnd.laxino.com
  host: hq-stg-sso-vdb01.laxino.local
  port: 3306

staging1:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_staging
  username: rigi
  password: rigi
  host: sso-vdb01.stg1.ias.local
  port: 3306

ga0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_ga0
  username: rigi
  password: rigi.pa$$w0rd123
  host: sso-vdb01.ga0.ias.local
  port: 3306

sandbox0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: ph-snd-sso-vdb01.laxigames.com
  port: 6034

production0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: ph-prd-sso-vdb01.laxigames.com
  port: 6033

sandbox2:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: tw-snd-sso-vdb01.laxigames.local
  port: 6034

smartocean2:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: tw-prd-sso-vdb01.laxigames.local
  port: 6033

mockup0:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_mockup
  username: rigi
  password: rigi
  host: mo-mock-sso-vdb01.rnd.laxino.com
  port: 3306

sandbox3:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: mo-snd-sso-vdb01.lb.laxigames.local
  port: 6034

production3:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: mo-prd-sso-vdb01.lb.laxigames.local
  port: 6033

production4:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: mo-prd-sso-vdb01.ol.laxigames.local
  port: 6033

sandbox:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: mo-snd-sso-vdb01.platform.gamesource.local
  port: 6034

production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: mo-prd-sso-vdb01.platform.gamesource.local
  port: 6033

ias_prd:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: do-prd-sso-vdb01.idc.local
  port: 6033

sandbox5:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: sso-vdb01.snd5.gamesource.local
  port: 6034

sandbox6:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: sso-vdb01.snd6.gamesource.local
  port: 6034

cert1:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: sso-vdb01.cert1.idc.local
  port: 6033

production6:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: sso-vdb01.prd6.gamesource.local
  port: 6033

sandbox8:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: sso-vdb01.snd8.gamesource.local
  port: 6034

sandbox10:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: sso-vdb01.snd10.gamesource.local
  port: 6034

esbsandbox:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: esbrigi_sso_sandbox
  username: esbrigi
  password: esbrigi.pa$$w0rd123
  host: esb-sso-vdb01.snd10.gamesource.local
  port: 6034

production10:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_production
  username: rigi
  password: rigi.pa$$w0rd123
  host: sso-vdb01.prd10.gamesource.local
  port: 6033

production11:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: esbrigi_sso_production
  username: esbrigi
  password: esbrigi.pa$$w0rd123
  host: esb-sso-vdb01.prd11.gs.local
  port: 3306


sandbox9:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  database: rigi_sso_sandbox
  username: rigi
  password: rigi.pa$$w0rd123
  host: sso-vdb01.snd9.gamesource.local
  port: 6034
