hqidc_domain: &hqidc_domain
  domains:
    - {id: 1, name: 'mo.laxino.com'}
  domains_casinos:
    - {id: 1, domain_id: 1, casino_id: 20000}
    - {id: 2, domain_id: 1, casino_id: 20001}
    - {id: 3, domain_id: 1, casino_id: 1000}
    - {id: 4, domain_id: 1, casino_id: 1003}
    - {id: 5, domain_id: 1, casino_id: 1007}
    - {id: 6, domain_id: 1, casino_id: 1011}
    - {id: 7, domain_id: 1, casino_id: 1012}
    - {id: 8, domain_id: 1, casino_id: 1014}
    - {id: 9, domain_id: 1, casino_id: 1016}
    - {id: 10, domain_id: 1, casino_id: 1017}
    - {id: 11, domain_id: 1, casino_id: 1018}
    - {id: 12, domain_id: 1, casino_id: 1021}
    - {id: 13, domain_id: 1, casino_id: 1035}
    - {id: 14, domain_id: 1, casino_id: 1036}
    - {id: 15, domain_id: 1, casino_id: 1037}
    - {id: 16, domain_id: 1, casino_id: 1038}
    - {id: 17, domain_id: 1, casino_id: 1039}
    - {id: 18, domain_id: 1, casino_id: 1040}
    - {id: 19, domain_id: 1, casino_id: 1041}
    - {id: 20, domain_id: 1, casino_id: 1042}
    - {id: 21, domain_id: 1, casino_id: 1043}
    - {id: 22, domain_id: 1, casino_id: 1045}
    - {id: 23, domain_id: 1, casino_id: 1046}
    - {id: 24, domain_id: 1, casino_id: 1047}
    - {id: 25, domain_id: 1, casino_id: 1048}
    - {id: 26, domain_id: 1, casino_id: 1052}
    - {id: 27, domain_id: 1, casino_id: 20002}

mockup_domain: &mockup_domain
  domains:
    - {id: 1, name: 'mo.laxino.com'}
  domains_casinos:
    - {id: 1, domain_id: 1, casino_id: 1000}
    - {id: 2, domain_id: 1, casino_id: 20000}
    - {id: 3, domain_id: 1, casino_id: 20001}
    - {id: 4, domain_id: 1, casino_id: 20002}       

twidc_domain: &twidc_domain
  domains:
    - {id: 1, name: '777iportal.local'}
  domains_casinos:
    - {id: 1, domain_id: 1, casino_id: 1000}

phidc_domain: &phidc_domain
  domains:
    - {id: 1, name: '888iportal.local'}
  domains_casinos:
    - {id: 1, domain_id: 1, casino_id: 1000}

moidc_domain: &moidc_domain
  domains:
    - {id: 1, name: 'gamesourcecloud.local'}
  domains_casinos:
    - {id: 1, domain_id: 1, casino_id: 10000}
    - {id: 2, domain_id: 1, casino_id: 1000}

vcidc_domain: &vcidc_domain
  domains:
    - {id: 1, name: 'laxigames.local'}
  domains_casinos:
    - {id: 1, domain_id: 1, casino_id: 1000}

test:
  <<: *hqidc_domain

development:
  <<: *hqidc_domain

integration0:
  <<: *hqidc_domain

staging0:
  <<: *hqidc_domain

sandbox0:
  <<: *phidc_domain

production0:
  <<: *phidc_domain

mockup0:
  <<: *mockup_domain

sandbox2:
  <<: *twidc_domain

smartocean2:
  <<: *twidc_domain

sandbox3: 
  <<: *moidc_domain

production3:
  <<: *moidc_domain

production4:
  <<: *vcidc_domain
