hqidc_domain: &hqidc_domain
  domains:
    - {id: 1, name: 'mo.laxino.com', licensee_id: 1000}

mockup_domain: &mockup_domain
  domains:
    - {id: 1, name: 'mo.laxino.com', licensee_id: 1000}    

twidc_domain: &twidc_domain
  domains:
    - {id: 1, name: '777iportal.local', licensee_id: 1000}

phidc_domain: &phidc_domain
  domains:
    - {id: 1, name: '888iportal.local', licensee_id: 1000}

moidc_domain: &moidc_domain
  domains:
    - {id: 1, name: 'gamesourcecloud.local', licensee_id: 1000}

vcidc_domain: &vcidc_domain
  domains:
    - {id: 1, name: 'laxigames.local', licensee_id: 1000}

test:
  <<: *hqidc_domain

development:
  <<: *hqidc_domain

integration0:
  <<: *hqidc_domain

staging0:
  <<: *hqidc_domain

sandbox0:
  <<: *phidc_domain

production0:
  <<: *phidc_domain

mockup0:
  <<: *mockup_domain

sandbox2:
  <<: *twidc_domain

smartocean2:
  <<: *twidc_domain

sandbox3: 
  <<: *moidc_domain

production3:
  <<: *moidc_domain

production4:
  <<: *vcidc_domain
