hqidc_domain: &hqidc_domain
  domains:
    - {id: 1, name: 'mo.laxino.com'}
  licensees:
    - {id: 1000, domain_id: 1}

stg1_domain: &hqidc_domain
  domains:
    - {id: 1, name: 'ias.local'}
  licensees:
    - {id: 1000, domain_id: 1}

mockup_domain: &mockup_domain
  domains:
    - {id: 1, name: 'mo.laxino.com'}
  licensees:
    - {id: 1000, domain_id: 1}

twidc_domain: &twidc_domain
  domains:
    - {id: 1, name: '777iportal.local'}
  licensees:
    - {id: 1000, domain_id: 1}

phidc_domain: &phidc_domain
  domains:
    - {id: 1, name: '888iportal.local'}
  licensees:
    - {id: 1000, domain_id: 1}

moidc_domain: &moidc_domain
  domains:
    - {id: 1, name: 'gamesourcecloud.local'}
  licensees:
    - {id: 1000, domain_id: 1}

vcidc_domain: &vcidc_domain
  domains:
    - {id: 1, name: 'laxigames.local'}
  licensees:
    - {id: 1000, domain_id: 1}

ias_domain: &ias_domain
  domains:
    - {id: 1, name: 'idc.local'}
  licensees:
    - {id: 1000, domain_id: 1}

test:
  <<: *hqidc_domain

development:
  <<: *hqidc_domain

integration0:
  <<: *hqidc_domain

staging0:
  <<: *hqidc_domain

staging1:
  <<: *stg1_domain

sandbox0:
  <<: *phidc_domain

production0:
  <<: *phidc_domain

mockup0:
  <<: *mockup_domain

sandbox2:
  <<: *twidc_domain

smartocean2:
  <<: *twidc_domain

sandbox3:
  <<: *moidc_domain

production3:
  <<: *moidc_domain

production4:
  <<: *vcidc_domain

sandbox:
  <<: *moidc_domain

production:
  <<: *moidc_domain

ias_prd:
  <<: *ias_domain
