common: &default_tables
  tables:
  - source_table: properties
    columns:
      name:
      description:

development:
- source_db:
    adapter: mysql2
    port: 3306
    username: kamet
    password: amskamet
    database: dhaulagiri_slms_development
    host: dev-cons-db01.rnd.laxino.com
  <<: *default_tables

test:
- source_db:
    adapter: mysql2
    port: 3306
    username: kamet
    password: amskamet
    database: dhaulagiri_slms_test
    host: dev-cons-db01.rnd.laxino.com
  <<: *default_tables

integration0:
- source_db:
    adapter: mysql2
    port: 3306
    username: kamet
    password: amskamet
    database: dhaulagiri_slms_integration
    host: int-cons-vdb01.rnd.laxino.com
  <<: *default_tables

staging0:
- source_db:
    adapter: mysql2
    port: 3306
    username: laxino
    password: laxino
    database: dhaulagiri_slms_staging
    host: stg-cons-vdb01.rnd.laxino.com
  <<: *default_tables

production0:
- source_db:
    adapter: mysql2
    port: 6033
    username: dhaulagiri
    password: dhaulagiri.pa$$w0rd123
    database: dhaulagiri_slms_production
    host: prd-sms-vdb01.prod.laxigames.com
  <<: *default_tables

sandbox0:
- source_db:
    adapter: mysql2
    port: 6034
    username: dhaulagiri
    password: dhaulagiri.pa$$w0rd123
    database: dhaulagiri_slms_sandbox
    host: snd-cons-db01.sandbox.laxigames.com
  <<: *default_tables

sandbox2:
- source_db:
    adapter: mysql2
    port: 6034
    username: dhaulagiri
    password: dhaulagiri.pa$$w0rd123
    database: dhaulagiri_slms_sandbox
    host: snd-cons-vdb01.sbox.so.idc02.laxigames.local
  <<: *default_tables

smartocean2:
- source_db:
    adapter: mysql2
    port: 6033
    username: dhaulagiri
    password: dhaulagiri.pa$$w0rd123
    database: dhaulagiri_slms_production
    host: prd-sms-vdb01.prod.so.idc02.laxigames.local
  <<: *default_tables
