default: &default
  laxino:
    domain:
      name: 'mo.laxino.com'
    auth_source:
      token: '10.10.5.45'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        host: 'modc03.mo.laxino.com'
        port: 3268
        account: 'svc_idc_ldap@mo.laxino.com'
        password: '$vc_1dc_1daP'
        admin_account: 'svc_idc_ldap@mo.laxino.com'
        admin_password: '$vc_1dc_1daP'
        base_dn: 'dc=mo, dc=laxino, dc=com'

development:
  <<: *default

integration0:
  <<: *default

staging0:
  <<: *default

staging1: &staging1
  laxino:
      domain:
        name: 'ias.local'
      auth_source:
        token: '*'
        type: 'Ldap'
      auth_source_detail:
        name: 'laxino_ldap'
        data:
          host: 'vdc01'
          port: 3268
          account: 'svc_idc_ldap@ias.local'
          password: 'I@s.1daP'
          admin_account: 'svc_idc_ldap@ias.local'
          admin_password: 'I@s.1daP'
          base_dn: 'dc=ias, dc=local'

ga0:
  <<: *staging1

sandbox0: &sandbox0
  laxino:
    domain:
      name: '888iportal.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'ph-prd-exdc01.888iportal.local'
        port: 3268
        account: 'svc_idc_ldap@888iportal.local'
        password: '$vc_1dc_1daP'
        admin_account: 'svc_idc_ldap@888iportal.local'
        admin_password: '$vc_1dc_1daP'
        base_dn: 'dc=888iportal, dc=local'

production0:
  <<: *sandbox0

sandbox2: &sandbox2
  laxino:
    domain:
      name: '777iportal.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'tw-prd-exdc01.777iportal.local'
        port: 3268
        account: 'svc_idc_ldap@777iportal.local'
        password: '$vc_1dc_1daP'
        admin_account: 'svc_idc_ldap@777iportal.local'
        admin_password: '$vc_1dc_1daP'
        base_dn: 'dc=777iportal, dc=local'

smartocean2:
  <<: *sandbox2

sandbox3: &sandbox3
  laxino:
    domain:
      name: 'gamesourcecloud.local'
    auth_source:
      token: '202.86.130.178'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'mo-prd-dc01.gamesourcecloud.local'
        port: 3268
        account: 'svc_idc_ldap@gamesourcecloud.local'
        password: '$vc_1dc_1daP'
        admin_account: 'svc_idc_ldap@gamesourcecloud.local'
        admin_password: '$vc_1dc_1daP'
        base_dn: 'dc=gamesourcecloud, dc=local'

production3:
  laxino:
    domain:
      name: 'gamesourcecloud.local'
    auth_source:
      token: '192.168.103.254'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'mo-prd-dc01.gamesourcecloud.local'
        port: 3268
        account: 'svc_idc_ldap@gamesourcecloud.local'
        password: '$vc_1dc_1daP'
        admin_account: 'svc_idc_ldap@gamesourcecloud.local'
        admin_password: '$vc_1dc_1daP'
        base_dn: 'dc=gamesourcecloud, dc=local'

production4:
  laxino:
    domain:
      name: 'laxigames.local'
    auth_source:
      token: '2.2.2.2'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxigames.local'
      data:
        domain_name: 'laxigames.local'
        name: 'laxino_ldap'
        host: 'mo-mgt-vdc01.laxigames.local'
        port: 3268
        account: 'svc_idc_ldap@laxigames.local'
        password: '$vc_1dc_1daP'
        admin_account: ""
        admin_password: ""
        base_dn: 'dc=laxigames, dc=local'

production6:
  laxino:
    domain:
      name: 'gamesourcecloud.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'mo-prd-dc01.gamesourcecloud.local'
        port: 3268
        account: 'svc_idc_ldap@gamesourcecloud.local'
        password: '$vc_1dc_1daP'
        admin_account: 'svc_idc_ldap@gamesourcecloud.local'
        admin_password: '$vc_1dc_1daP'
        base_dn: 'dc=gamesourcecloud, dc=local'

sandbox:
  <<: *sandbox3

production:
  <<: *sandbox3

ias_prd:
  laxino:
    domain:
      name: 'idc.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'hq-prd-dc01.idc.local'
        port: 3268
        account: 'svc_idc_ldap@idc.local'
        password: '$vc_1dc_1daP'
        admin_account: 'svc_idc_ldap@idc.local'
        admin_password: '$vc_1dc_1daP'
        base_dn: 'dc=idc, dc=local'

cert1:
  laxino:
    domain:
      name: 'idc.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'hq-prd-dc01.idc.local'
        port: 3268
        account: 'svc_idc_ldap@idc.local'
        password: '$vc_1dc_1daP'
        admin_account: 'svc_idc_ldap@idc.local'
        admin_password: '$vc_1dc_1daP'
        base_dn: 'dc=idc, dc=local'

sandbox5:
  <<: *sandbox0

sandbox6:
  laxino:
    domain:
      name: 'gamesourcecloud.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'mo-prd-dc11.gamesourcecloud.local'
        port: 3268
        account: 'svc_idc_ldap@gamesourcecloud.local'
        password: '$vc_1dc_1daP'
        admin_account: 'svc_idc_ldap@gamesourcecloud.local'
        admin_password: '$vc_1dc_1daP'
        base_dn: 'dc=gamesourcecloud, dc=local'

sandbox8:
  laxino:
    domain:
      name: 'gamesourcecloud.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'ldap-app01.gamesourcecloud.local'
        port: 389
        account: 'svc_idc_ldap@gamesourcecloud.local'
        password: 'Svc_1dc_1daP'
        admin_account: 'svc_idc_ldap@gamesourcecloud.local'
        admin_password: 'Svc_1dc_1daP'
        base_dn: 'dc=gamesourcecloud, dc=local'

sandbox10:
  laxino:
    domain:
      name: 'gamesourcecloud.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'snd10-vdc01.gamesourcecloud.local'
        port: 3268
        account: 'svc_idc_ldap@gamesourcecloud.local'
        password: 'Svc_1dc_1daP'
        admin_account: 'svc_idc_ldap@gamesourcecloud.local'
        admin_password: 'Svc_1dc_1daP'
        base_dn: 'dc=gamesourcecloud, dc=local'

esbsandbox:
  laxino:
    domain:
      name: 'gamesourcecloud.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'snd10-vdc01.gamesourcecloud.local'
        port: 3268
        account: 'svc_idc_ldap@gamesourcecloud.local'
        password: 'Svc_1dc_1daP'
        admin_account: 'svc_idc_ldap@gamesourcecloud.local'
        admin_password: 'Svc_1dc_1daP'
        base_dn: 'dc=gamesourcecloud, dc=local'

sandbox9:
  laxino:
    domain:
      name: 'gamesourcecloud.local'
    auth_source:
      token: '*'
      type: 'Ldap'
    auth_source_detail:
      name: 'laxino_ldap'
      data:
        name: 'laxino_ldap'
        host: 'snd9-vdc01.gamesourcecloud.local'
        port: 389
        account: 'svc_idc_ldap@gamesourcecloud.local'
        password: 'Svc_1dc_1daP'
        admin_account: 'svc_idc_ldap@gamesourcecloud.local'
        admin_password: 'Svc_1dc_1daP'
        base_dn: 'dc=gamesourcecloud, dc=local'