hqidc_domain: &hqidc_domain
  licensees:
    - {id: 1000, name: 'LAXINO'}
   
  casinos:
    - {id: 1000, name: 'LAXINO', licensee_id: 1000}
 
  properties:
    - {id: 1000, name: 'LAXINO', casino_id: 1000}
  
test:
  <<: *hqidc_domain

development:
  <<: *hqidc_domain

integration0:
  <<: *hqidc_domain

staging0:
  <<: *hqidc_domain

sandbox0:
  <<: *hqidc_domain

production0:
  <<: *hqidc_domain

mockup0:
  <<: *hqidc_domain

sandbox2:
  <<: *hqidc_domain

smartocean2:
  <<: *hqidc_domain

sandbox3: 
  <<: *hqidc_domain

production3:
  <<: *hqidc_domain

production4:
  <<: *hqidc_domain
